// This file is auto-generated by build.sh during Cloudflare Pages deploy.
// The placeholder values below are only used if you open the site locally
// without going through Cloudflare (auth will not work in that case).
window.SUPABASE_URL = "";
window.SUPABASE_ANON_KEY = "";
